include_guard(GLOBAL)

if(${CMAKE_HOST_SYSTEM_NAME} STREQUAL "Linux")
    set(CMAKE_SYSTEM_NAME Linux)
elseif(XCODE)
    message(FATAL_ERROR "Currently MacOS platform is not supported.")
else()
    message(STATUS "Selecting Windows as default platform.")
    target_link_libraries(${CMAKE_PROJECT_NAME} wsock32)
    target_link_libraries(${CMAKE_PROJECT_NAME} ws2_32)
    target_link_libraries(${CMAKE_PROJECT_NAME} advapi32)
    set(CMAKE_SYSTEM_NAME Windows)
endif()    
unset(COMPILER_PREFIX)
